# Generated by Django 2.2.21 on 2021-06-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application_form", "0019_alter_field_apartments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="applicants_count",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="applicants count"
            ),
        ),
    ]
