# Generated by Django 2.2.24 on 2021-08-24 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartment", "0006_alter_apartment_number_to_charfield"),
        ("application_form", "0027_application_profile_nullable"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReservationQueue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "apartment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queue",
                        to="apartment.Apartment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReservationQueueChangeEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position_change",
                    models.IntegerField(verbose_name="position change"),
                ),
                (
                    "position_change_reason",
                    models.CharField(
                        max_length=255, verbose_name="position change reason"
                    ),
                ),
                (
                    "queue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_events",
                        to="application_form.ReservationQueue",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReservationQueueApplication",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "queue_position",
                    models.IntegerField(verbose_name="position in queue"),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queue_applications",
                        to="application_form.Application",
                    ),
                ),
                (
                    "queue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queue_applications",
                        to="application_form.ReservationQueue",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("queue", "application"),
                    ("queue", "queue_position"),
                },
            },
        ),
    ]
